### ISSUE TITLE
unable to install via brew

### ISSUE THREAD

**Issue by duxing** [lingrino/vaku#138]
command used to install:
 `brew install lingrino/tap/vaku`

got error message:

> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/lingrino/homebrew-tap/Formula/hoo.rb
hoo: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the lingrino/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/lingrino/homebrew-tap/Formula/hoo.rb:6
>
>Error: Cannot tap lingrino/tap: invalid syntax in tap!

OS: OS X Big Sur 11.6.4

**Comment by lingrino** [comment]
Hello @duxing thanks for creating the issue! It looks like I had an old unused formula that now has a deprecated field. I just deleted it. Could you try again?

**Comment by duxing** [comment]
@lingrino installation works now. thanks!
