### ISSUE TITLE
Filter for Folder Copy to only copy based on Key Regex

### ISSUE THREAD

**Issue by Kuraiou** [Lingrino/vaku#26]
I would like to be able to limit the results of the folder copy only to those whose key matches a particular regular expression.

### use case

For the launch of TD, we needed to copy small subsets of common variables (e.g. RUBY_GC_MALLOC_MIN, RUBY_GC_MALLOC_MAX, etc.), and having regular expression selection of keys would have streamlined this work significantly.

**Comment by Lingrino** [comment]
This is best accomplished with a folder list -> regex -> folder write using the API. The CLI doesn't support writes directly, but the API is perfect for that.
