### ISSUE TITLE
Vaku (homebrew version) will not execute on Fedora Linux or WSL

### ISSUE THREAD

**Issue by synaptis** [lingrino/vaku#53]
**Issue**
After successfully installing linuxbrew, ensuring PATH is set correctly, installing vaku and setting  /home/linuxbrew/.linuxbrew/Cellar/vaku/1.1.1/bin/vaku to be executable attempting to run vaku fails with the following error:

`$ vaku -h`
`bash: /home/linuxbrew/.linuxbrew/bin/vaku: cannot execute binary file: Exec format error`

**Steps Taken**
`$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`
`$ test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)`
`$ test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)`
`$ test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile`
`$ brew install lingrino/tap/vaku`
`$ vaku -h`
`bash: /home/linuxbrew/.linuxbrew/bin/vaku: Permission denied`
`$ chmod 555 /home/linuxbrew/.linuxbrew/Cellar/vaku/1.1.1/bin/vaku`
`$ vaku -h`
`bash: /home/linuxbrew/.linuxbrew/bin/vaku: cannot execute binary file: Exec format error`

**Additional Info**
The vault binary included with the homebrew version of vaku executes without issue.
`$ vault -h`
`Usage: vault <command> [args]`
`<snip>`

`file /home/linuxbrew/.linuxbrew/Cellar/vault/1.2.2/bin/vault`
`/home/linuxbrew/.linuxbrew/Cellar/vault/1.2.2/bin/vault: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=SO1z1SDfi0jHi9Es0U-L/loeYoDLiiRizqE3Ftg_h/9pGJhh4sewGN5N0Hnyjp/KJ4ke0EOnHGwhY6QVTx8, not stripped`

`$ file /home/linuxbrew/.linuxbrew/Cellar/vaku/1.1.1/bin/vaku`
`/home/linuxbrew/.linuxbrew/Cellar/vaku/1.1.1/bin/vaku: Mach-O 64-bit x86_64 executable`

** System Info**
This issue has presented on Fedora 30 and in the Pengwin (Debian) WSL distribution.

`$ uname -a`
`Linux hostname 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux`

`$ uname -a`
`Linux hostname.domain.local 5.2.8-200.fc30.x86_64 #1 SMP Sat Aug 10 13:21:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by lingrino** [comment]
Hi @synaptis really sorry about the long wait with this issue. Somehow my notifications for this repo got turned off.

The good news is, I think this was previously unsupported in https://github.com/goreleaser/goreleaser/, which I use to build the taps. However I think that is fixed with the latest release, which should add a section for Linux in [the tap](https://github.com/lingrino/homebrew-tap/blob/master/Formula/vaku.rb).

Do you mind trying again with the latest version (`1.2.0`)? Thanks!

**Comment by synaptis** [comment]
Hey @lingrino, no worries at all. We actually resolved this by grabbing the source and building the vaku binary for Linux. Pretty simple to do, works great and we didn't need homebrew.

We are looking at building a web app around vaku as a way of delivering the Vault search functionality to our users, lack of search is the biggest complaint we have around Vault.

**Comment by lingrino** [comment]
That's great, glad to hear you're using it!
