### ISSUE TITLE
output with text is not sorted.

### ISSUE THREAD

**Issue by hixichen** [lingrino/vaku#62]
json output is sorted and always same. 
But output with text is not sorted.
```
vaku folder read my-path/ -T -o text
```

**Comment by lingrino** [comment]
In the API the only sorted output is anything that returns a `[]string` (`pathList`, `folderSearch`). With the CLI the json output is sorted when I marshall the API output into JSON, but with text output I just loop over the results and print them ([here](https://github.com/lingrino/vaku/blob/master/cmd/helpers.go#L134)). I agree it would be nice for CLI results to be sorted by default, but it's not something I'm going to add. Feel free to submit a PR and I'll be happy to review. Thanks!

**Comment by lingrino** [comment]
I'm working on a version 2 of vaku that will include a cli option for sorting output. SHould be ready in ~1 month but timeline could change.

**Comment by lingrino** [comment]
Version 2 was just release and sorting is now turned on by default. Thanks for filing this issue 😄
