### ISSUE TITLE
For CMD like folder copy,  VAULT_TOKEN or ~/.vault-token should not be mandatory 

### ISSUE THREAD

**Issue by hixichen** [lingrino/vaku#66]
For folder copy from one namespace to another namespace. 

VAULT_TOKEN or ~/.vault-token should not be mandatory as vaku will use source token and target token. 

```
vaku folder copy $path/ $path/ --use-source-target-params --source-address=$source_address --source-token=$source_token --source-namespace=$source_namespace --target-address=$target_address --target-token=$target_token --target-namespace=$target_namespace -o=text
```

**Comment by lingrino** [comment]
Thanks for the issue! I agree this can be improved. A `v2` is currently being worked on and I will track this with that release.

**Comment by lingrino** [comment]
Version 2 was just released and resolves this issue! Keep in mind that there are other breaking changes in this version you may need to adjust to. Thanks for your contribution 😄
